/**
 * Liste des baleines crypto à suivre
 * Configuration des adresses importantes à monitorer
 */

export const CRYPTO_WHALES = {
    whales: [
        {
            name: "US Government Silk Road Seizure",
            type: "Government",
            chain: "BTC",
            address: "bc1qjet9suh6lpyu8uwcseywkr9zcn55lawp83wzde",
            notes: "Saisie gouvernementale US - Silk Road",
        },
        {
            name: "Donald Trump's Wallet",
            type: "Founder",
            chain: "ETH",
            address: "0x94845333028B1204Fbe14E1278Fd4Adde46B22ce",
            notes: "Portefeuille de Donald Trump - Source: Arkham Intel",
        },
        {
            name: "US Government Bitfinex Hack Seizure",
            type: "Government",
            chain: "BTC",
            address: "bc1qazcm763858nkj2dj986etajv6wquslv8uxwczt",
            notes: "Saisie gouvernementale US - Bitfinex Hack",
        },
        // ==================== BITINFOCHARTS RICH LIST ====================
        {
            name: "Binance Cold Wallet #1",
            type: "Exchange",
            chain: "BTC",
            address: "34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo",
            notes: "Source: BitInfoCharts Rich List - Rank #1 - 248,598 BTC",
        },
        {
            name: "Binance Cold Wallet #2",
            type: "Exchange",
            chain: "BTC",
            address: "3M219KR5vEneNb47ewrPfWyb5jQ2DjxRP6",
            notes: "Source: BitInfoCharts Rich List - Rank #2 - 147,123 BTC",
        },
        {
            name: "Robinhood Cold Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "bc1ql49ydapnjafl5t2cp9zqpjwe6pdgmxy98859v2",
            notes: "Source: BitInfoCharts Rich List - Rank #3 - 140,575 BTC",
        },
        {
            name: "Bitfinex Cold Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "bc1qgdjqv0av3q56jvd82tkdjpy7gdp9ut8tlqmgrpmv24sq90ecnvqqjwvw97",
            notes: "Source: BitInfoCharts Rich List - Rank #4 - 130,010 BTC",
        },
        {
            name: "Bitfinex Hack Recovery",
            type: "Hack",
            chain: "BTC",
            address: "bc1qazcm763858nkj2dj986etajv6wquslv8uxwczt",
            notes: "Source: BitInfoCharts Rich List - Rank #5 - 94,643 BTC",
        },
        {
            name: "Tether Treasury",
            type: "Stablecoin",
            chain: "BTC",
            address: "bc1qjasf9z3h7w3jspkhtgatgpyvvzgpa2wwd2lr0eh5tx44reyn2k7sfc27a4",
            notes: "Source: BitInfoCharts Rich List - Rank #7 - 87,296 BTC",
        },
        {
            name: "MtGox Hack",
            type: "Hack",
            chain: "BTC",
            address: "1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF",
            notes: "Source: BitInfoCharts Rich List - Rank #8 - 79,957 BTC",
        },
        {
            name: "Binance BTCB Reserve",
            type: "Exchange",
            chain: "BTC",
            address: "3LYJfcfHPXYJreMsASk2jkn69LWEYKzexb",
            notes: "Source: BitInfoCharts Rich List - Rank #11 - 68,200 BTC",
        },
        {
            name: "Mr.100",
            type: "Trader",
            chain: "BTC",
            address: "1Ay8vMC7R1UbyCCZRVULMV7iQpHSAbguJP",
            notes: "Source: BitInfoCharts Rich List - Rank #12 - 61,374 BTC",
        },
        {
            name: "OKEx",
            type: "Exchange",
            chain: "BTC",
            address: "3MgEAFWu1HKSnZ5ZsC8qf61ZW18xrP5pgd",
            notes: "Source: BitInfoCharts Rich List - Rank #13 - 56,110 BTC",
        },
        {
            name: "Coincheck",
            type: "Exchange",
            chain: "BTC",
            address: "bc1q4j7fcl8zx5yl56j00nkqez9zf3f6ggqchwzzcs5hjxwqhsgxvavq3qfgpr",
            notes: "Source: BitInfoCharts Rich List - Rank #19 - 41,808 BTC",
        },
        {
            name: "Binance Cold Wallet #3",
            type: "Exchange",
            chain: "BTC",
            address: "3LQUu4v9z6KNch71j7kbj8GPeAGUo1FW6a",
            notes: "Source: BitInfoCharts Rich List - Rank #21 - 37,927 BTC",
        },
        {
            name: "US Government Bitfinex Hack Recovery (FBI)",
            type: "Government",
            chain: "BTC",
            address: "bc1qazcm763858nkj2dj986etajv6wquslv8uxwczt"
        },
        {
            name: "UK Government Zhimin Qian & Jian Wen Fraud Funds",
            type: "Government",
            chain: "BTC",
            address: "bc1q4vxn43l44h30nkluqfxd9eckf45vr2awz38lwa",
            notes: "Source: BitInfoCharts Rich List - Rank #22 - 36,000 BTC",
        },
        {
            name: "Binance Pool",
            type: "Mining",
            chain: "BTC",
            address: "bc1qx9t2l3pyny2spqpqlye8svce70nppwtaxwdrp4",
            notes: "Source: BitInfoCharts Rich List - Rank #25 - 31,643 BTC",
        },
        {
            name: "Binance Cold Wallet #4",
            type: "Exchange",
            chain: "BTC",
            address: "3FHNBLobJnbCTFTVakh5TXmEneyf5PT61B",
            notes: "Source: BitInfoCharts Rich List - Rank #27 - 31,275 BTC",
        },
        {
            name: "Crypto.com Cold Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "bc1qr4dl5wa7kl8yu792dceg9z5knl2gkn220lk7a9",
            notes: "Source: BitInfoCharts Rich List - Rank #43 - 19,594 BTC",
        },
        {
            name: "Bitbank Cold Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "bc1qx2x5cqhymfcnjtg902ky6u5t5htmt7fvqztdsm028hkrvxcl4t2sjtpd9l",
            notes: "Source: BitInfoCharts Rich List - Rank #44 - 19,528 BTC",
        },
        {
            name: "Ceffu Cold Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "bc1q32lyrhp9zpww22phqjwwmelta0c8a5q990ghs6",
            notes: "Source: BitInfoCharts Rich List - Rank #47 - 16,845 BTC",
        },
        {
            name: "Binance Cold Wallet #5",
            type: "Exchange",
            chain: "BTC",
            address: "1PJiGp2yDLvUgqeBsuZVCBADArNsk6XEiw",
            notes: "Source: BitInfoCharts Rich List - Rank #49 - 16,391 BTC",
        },
        {
            name: "Binance Cold Wallet #6",
            type: "Exchange",
            chain: "BTC",
            address: "34HpHYiyQwg69gFmCq2BGHjF1DZnZnBeBP",
            notes: "Source: BitInfoCharts Rich List - Rank #50 - 16,307 BTC",
        },
        {
            name: "Bitfinex Cold Wallet #2",
            type: "Exchange",
            chain: "BTC",
            address: "3JZq4atUahhuA9rLhXLMhhTo133J9rF97j",
            notes: "Source: BitInfoCharts Rich List - Rank #51 - 16,000 BTC",
        },
        {
            name: "OKEx #2",
            type: "Exchange",
            chain: "BTC",
            address: "3FM9vDYsN2iuMPKWjAcqgyahdwdrUxhbJ3",
            notes: "Source: BitInfoCharts Rich List - Rank #53 - 15,718 BTC",
        },
        {
            name: "Binance Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h",
            notes: "Source: BitInfoCharts Rich List - Rank #54 - 15,083 BTC",
        },
        {
            name: "BitMEX",
            type: "Exchange",
            chain: "BTC",
            address: "bc1qchctnvmdva5z9vrpxkkxck64v7nmzdtyxsrq64",
            notes: "Source: BitInfoCharts Rich List - Rank #60 - 13,315 BTC",
        },
        {
            name: "UK Government Confiscated #2",
            type: "Government",
            chain: "BTC",
            address: "bc1q4vxn43l44h30nkluqfxd9eckf45vr2awz38lwa",
            notes: "Source: BitInfoCharts Rich List - Rank #62 - 13,003 BTC",
        },
        {
            name: "Bitfinex Hack Recovery #2",
            type: "Hack",
            chain: "BTC",
            address: "bc1qkmk4v2xn29yge68fq6zh7gvfdqrvpq3v3p3y0s",
            notes: "Source: BitInfoCharts Rich List - Rank #64 - 12,267 BTC",
        },
        {
            name: "Binance Pool #2",
            type: "Mining",
            chain: "BTC",
            address: "1Q8QR5k32hexiMQnRgkJ6fmmjn5fMWhdv9",
            notes: "Source: BitInfoCharts Rich List - Rank #74 - 10,217 BTC",
        },
        {
            name: "OKX #1",
            type: "Exchange",
            chain: "BTC",
            address: "1DcT5Wij5tfb3oVViF8mA8p4WrG98ahZPT",
            notes: "Source: BitInfoCharts Rich List - Rank #91 - 10,000 BTC",
        },
        {
            name: "OKX #2",
            type: "Exchange",
            chain: "BTC",
            address: "1CY7fykRLWXeSbKB885Kr4KjQxmDdvW923",
            notes: "Source: BitInfoCharts Rich List - Rank #92 - 10,000 BTC",
        },
        {
            name: "MicroStrategy Cold Wallet #1",
            type: "Institution",
            chain: "BTC",
            address: "1LQoWv2",
            notes: "Portefeuille froid MicroStrategy",
            incomplete: true,
        },
        {
            name: "MicroStrategy Cold Wallet #2",
            type: "Institution",
            chain: "BTC",
            address: "1P5ZED",
            notes: "Portefeuille froid MicroStrategy #2",
            incomplete: true,
        },
        {
            name: "Grayscale Bitcoin Trust",
            type: "Institution",
            chain: "BTC",
            address: "3QJmnh",
            notes: "Grayscale Bitcoin Trust",
            incomplete: true,
        },
        {
            name: "Binance Cold Wallet #1",
            type: "Exchange",
            chain: "BTC",
            address: "bc1q3fjfk3",
            notes: "Portefeuille froid Binance",
            incomplete: true,
        },
        {
            name: "Binance Cold Wallet #2",
            type: "Exchange",
            chain: "BTC",
            address: "3NqWc8",
            notes: "Portefeuille froid Binance #2",
            incomplete: true,
        },
        {
            name: "Binance BTC Hot Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "bc1q2u5",
            notes: "Portefeuille chaud Binance BTC",
            incomplete: true,
        },
        {
            name: "Coinbase Cold Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "3QJmnh",
            notes: "Portefeuille froid Coinbase",
            incomplete: true,
        },
        {
            name: "Kraken BTC Whale",
            type: "Exchange",
            chain: "BTC",
            address: "bc1qm8qu",
            notes: "Baleine Kraken BTC",
            incomplete: true,
        },
        {
            name: "Bitfinex Cold Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "bc1qxy2kg",
            notes: "Portefeuille froid Bitfinex",
            incomplete: true,
        },
        {
            name: "Blockstream Mining Address #1",
            type: "Mining",
            chain: "BTC",
            address: "1KFHE7w8B",
            notes: "Adresse de minage Blockstream",
            incomplete: true,
        },
        {
            name: "Early Miner #1 (Hal Finney cluster)",
            type: "Early Miner",
            chain: "BTC",
            address: "1PSSGeFHDnKNxiEyFrD1wcEaHr9hrQDDWc",
            notes: "Cluster Hal Finney - Early miner",
        },
        {
            name: "Early Whale #2",
            type: "Early Miner",
            chain: "BTC",
            address: "1FeexV6bAHb8ybZjqQMjJrcCrHGW9Sb6uF",
            notes: "Baleine précoce #2",
        },
        {
            name: "Satoshi Era Whale #1",
            type: "Early Miner",
            chain: "BTC",
            address: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
            notes: "Baleine de l'ère Satoshi",
        },
        {
            name: "MtGox Trustee",
            type: "Institution",
            chain: "BTC",
            address: "1JbezK",
            notes: "Trustee MtGox",
            incomplete: true,
        },
        // ============ ETHEREUM WHALES ============
        {
            name: "Vitalik Buterin Main Wallet",
            type: "Founder",
            chain: "ETH",
            address: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
            notes: "Portefeuille principal Vitalik Buterin",
        },
        {
            name: "Vitalik Donation Wallet",
            type: "Founder",
            chain: "ETH",
            address: "0xab5801a7d398351b8be11c439e05c5b3259aec9b",
            notes: "Portefeuille de donations Vitalik",
        },
        {
            name: "Ethereum Foundation Wallet",
            type: "Foundation",
            chain: "ETH",
            address: "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            notes: "Portefeuille Ethereum Foundation",
        },
        {
            name: "Binance ETH Whale #1",
            type: "Exchange",
            chain: "ETH",
            address: "0x9696f59e4d72e237be84ffd425dcad154bf96976",
            notes: "Baleine Binance ETH #1",
        },
        {
            name: "Binance ETH Whale #2",
            type: "Exchange",
            chain: "ETH",
            address: "0x28c6c06298d514db089934071355e5743bf21d60",
            notes: "Baleine Binance ETH #2",
        },
        {
            name: "Coinbase ETH Cold Wallet",
            type: "Exchange",
            chain: "ETH",
            address: "0x3cd751e6b0078be393132286c442345e5dc49699",
            notes: "Portefeuille froid Coinbase ETH",
        },
        {
            name: "Kraken ETH Cold Wallet",
            type: "Exchange",
            chain: "ETH",
            address: "0x0a869d79a7052c7f1b55a8ebabbea3420f0d1e13",
            notes: "Portefeuille froid Kraken ETH",
        },
        {
            name: "Tether Treasury",
            type: "Stablecoin",
            chain: "ETH",
            address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
            notes: "Trésorerie Tether (USDT)",
        },
        {
            name: "Circle USDC Treasury",
            type: "Stablecoin",
            chain: "ETH",
            address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
            notes: "Trésorerie Circle (USDC)",
        },
        {
            name: "Justin Sun Main Wallet",
            type: "Founder",
            chain: "ETH",
            address: "0x176f3dAb24a159341c0509bB36B833E7fdd0a132",
            notes: "Portefeuille principal Justin Sun",
        },
        {
            name: "a16z Crypto Wallet #1",
            type: "Venture Fund",
            chain: "ETH",
            address: "0x5a98fcbea516cf06857215779fd812ca3bef1b32",
            notes: "Portefeuille a16z Crypto #1",
        },
        {
            name: "a16z Crypto Wallet #2",
            type: "Venture Fund",
            chain: "ETH",
            address: "0xf977814e90da44bfa03b6295a0616a897441acec",
            notes: "Portefeuille a16z Crypto #2",
        },
        {
            name: "Paradigm Wallet #1",
            type: "Venture Fund",
            chain: "ETH",
            address: "0x79e1b5",
            notes: "Portefeuille Paradigm",
            incomplete: true,
        },
        {
            name: "Multicoin Capital Wallet #1",
            type: "Venture Fund",
            chain: "ETH",
            address: "0x79e2",
            notes: "Portefeuille Multicoin Capital",
            incomplete: true,
        },
        {
            name: "Polygon Foundation Wallet",
            type: "Foundation",
            chain: "ETH",
            address: "0x8d8e6abc0e6cd7b98d75ce30aebc9f2b1e7b82d5",
            notes: "Portefeuille Polygon Foundation",
        },
        {
            name: "Arbitrum DAO Treasury",
            type: "DAO",
            chain: "ETH",
            address: "0x4b6b256a4f1c7fa8f25c70a145d1c6a9dcd07025",
            notes: "Trésorerie Arbitrum DAO",
        },
        // Smart Money
        {
            name: "Smart Money Whale #1",
            type: "Trader",
            chain: "ETH",
            address: "0x5f7f53",
            notes: "Smart Money Trader #1",
            incomplete: true,
        },
        {
            name: "Smart Money Whale #2",
            type: "Trader",
            chain: "ETH",
            address: "0x999999",
            notes: "Smart Money Trader #2",
            incomplete: true,
        },
        {
            name: "Smart Money Whale #3",
            type: "Trader",
            chain: "ETH",
            address: "0xabc123",
            notes: "Smart Money Trader #3",
            incomplete: true,
        },
        {
            name: "Smart Money Whale #4",
            type: "Trader",
            chain: "ETH",
            address: "0xB1b1B1",
            notes: "Smart Money Trader #4",
            incomplete: true,
        },
        {
            name: "Smart Money Whale #5",
            type: "Trader",
            chain: "ETH",
            address: "0x111111",
            notes: "Smart Money Trader #5",
            incomplete: true,
        },
        // Plus d'exchanges
        {
            name: "Binance ETH Wallet #3",
            type: "Exchange",
            chain: "ETH",
            address: "0x21a31e",
            notes: "Binance ETH Wallet #3",
            incomplete: true,
        },
        {
            name: "Binance ETH Wallet #4",
            type: "Exchange",
            chain: "ETH",
            address: "0xf5bce",
            notes: "Binance ETH Wallet #4",
            incomplete: true,
        },
        {
            name: "Binance ETH Wallet #5",
            type: "Exchange",
            chain: "ETH",
            address: "0x56ed3",
            notes: "Binance ETH Wallet #5",
            incomplete: true,
        },
        {
            name: "Coinbase ETH Wallet #2",
            type: "Exchange",
            chain: "ETH",
            address: "0xfd540",
            notes: "Coinbase ETH Wallet #2",
            incomplete: true,
        },
        {
            name: "Coinbase ETH Wallet #3",
            type: "Exchange",
            chain: "ETH",
            address: "0x0c799",
            notes: "Coinbase ETH Wallet #3",
            incomplete: true,
        },
        {
            name: "Kraken ETH Wallet #2",
            type: "Exchange",
            chain: "ETH",
            address: "0x7f367",
            notes: "Kraken ETH Wallet #2",
            incomplete: true,
        },
        {
            name: "OKX ETH Whale",
            type: "Exchange",
            chain: "ETH",
            address: "0x2c8dc",
            notes: "OKX ETH Whale",
            incomplete: true,
        },
        {
            name: "Gate.io ETH Whale",
            type: "Exchange",
            chain: "ETH",
            address: "0x1bfe4",
            notes: "Gate.io ETH Whale",
            incomplete: true,
        },
        {
            name: "Kucoin ETH Whale",
            type: "Exchange",
            chain: "ETH",
            address: "0x2a3dd",
            notes: "Kucoin ETH Whale",
            incomplete: true,
        },
        // DAOs
        {
            name: "dYdX Treasury",
            type: "DAO",
            chain: "ETH",
            address: "0x1b7d3",
            notes: "Trésorerie dYdX",
            incomplete: true,
        },
        {
            name: "Uniswap Treasury",
            type: "DAO",
            chain: "ETH",
            address: "0xf9778",
            notes: "Trésorerie Uniswap",
            incomplete: true,
        },
        {
            name: "Aave Treasury",
            type: "DAO",
            chain: "ETH",
            address: "0x398ec",
            notes: "Trésorerie Aave",
            incomplete: true,
        },
        {
            name: "Curve DAO Treasury",
            type: "DAO",
            chain: "ETH",
            address: "0x1e33e",
            notes: "Trésorerie Curve DAO",
            incomplete: true,
        },
        {
            name: "Lido Treasury",
            type: "DAO",
            chain: "ETH",
            address: "0xae7ab",
            notes: "Trésorerie Lido",
            incomplete: true,
        },
        {
            name: "MakerDAO Treasury",
            type: "DAO",
            chain: "ETH",
            address: "0x66009",
            notes: "Trésorerie MakerDAO",
            incomplete: true,
        },
        // Plus de Smart Money
        {
            name: "Smart Money Whale #6",
            type: "Trader",
            chain: "ETH",
            address: "0x7a250",
            notes: "Smart Money Trader #6",
            incomplete: true,
        },
        {
            name: "Smart Money Whale #7",
            type: "Trader",
            chain: "ETH",
            address: "0xeeeeee",
            notes: "Smart Money Trader #7",
            incomplete: true,
        },
        // MEV Bots
        {
            name: "USDN Arbitrage Bot",
            type: "MEV Bot",
            chain: "ETH",
            address: "0x33e5c",
            notes: "Bot d'arbitrage USDN",
            incomplete: true,
        },
        {
            name: "MEV Bot Builder 0x01",
            type: "MEV Bot",
            chain: "ETH",
            address: "0x01dead",
            notes: "MEV Bot Builder 0x01",
            incomplete: true,
        },
        {
            name: "MEV Bot Builder 0x02",
            type: "MEV Bot",
            chain: "ETH",
            address: "0x02dead",
            notes: "MEV Bot Builder 0x02",
            incomplete: true,
        },
        {
            name: "Flashbots MEV Relay",
            type: "MEV",
            chain: "ETH",
            address: "0x9ed2a",
            notes: "Flashbots MEV Relay",
            incomplete: true,
        },
        // Autres blockchains
        {
            name: "Solana Foundation Treasury",
            type: "Foundation",
            chain: "SOL",
            address: "HhuVv3Rgq3",
            notes: "Trésorerie Solana Foundation",
            incomplete: true,
        },
        {
            name: "TRON Foundation Treasury",
            type: "Foundation",
            chain: "TRX",
            address: "TYMwiY4Z4",
            notes: "Trésorerie TRON Foundation",
            incomplete: true,
        },
        {
            name: "USDT TRON Treasury",
            type: "Stablecoin",
            chain: "TRX",
            address: "TDuo7z",
            notes: "Trésorerie USDT TRON",
            incomplete: true,
        },
        // Plus de baleines
        {
            name: "Whale ETH #30",
            type: "Trader",
            chain: "ETH",
            address: "0xabc000",
            notes: "Baleine ETH #30",
            incomplete: true,
        },
        {
            name: "Whale ETH #31",
            type: "Trader",
            chain: "ETH",
            address: "0xdef111",
            notes: "Baleine ETH #31",
            incomplete: true,
        },
        {
            name: "Whale ETH #32",
            type: "Trader",
            chain: "ETH",
            address: "0x999abc",
            notes: "Baleine ETH #32",
            incomplete: true,
        },
        // Plus de BTC
        {
            name: "Binance BTC Wallet #3",
            type: "Exchange",
            chain: "BTC",
            address: "3Jx3w",
            notes: "Binance BTC Wallet #3",
            incomplete: true,
        },
        {
            name: "Binance BTC Wallet #4",
            type: "Exchange",
            chain: "BTC",
            address: "bc1qm2",
            notes: "Binance BTC Wallet #4",
            incomplete: true,
        },
        {
            name: "Coinbase BTC Wallet #2",
            type: "Exchange",
            chain: "BTC",
            address: "3E8Kp",
            notes: "Coinbase BTC Wallet #2",
            incomplete: true,
        },
        {
            name: "OKX BTC Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "bc1qmw",
            notes: "OKX BTC Wallet",
            incomplete: true,
        },
        {
            name: "Gate.io BTC Wallet",
            type: "Exchange",
            chain: "BTC",
            address: "3F2sw",
            notes: "Gate.io BTC Wallet",
            incomplete: true,
        },
        {
            name: "Smart BTC Whale #1",
            type: "Trader",
            chain: "BTC",
            address: "1Ffz9",
            notes: "Smart BTC Whale #1",
            incomplete: true,
        },
        {
            name: "Smart BTC Whale #2",
            type: "Trader",
            chain: "BTC",
            address: "bc1qc5",
            notes: "Smart BTC Whale #2",
            incomplete: true,
        },
        {
            name: "Smart BTC Whale #3",
            type: "Trader",
            chain: "BTC",
            address: "bc1qn9",
            notes: "Smart BTC Whale #3",
            incomplete: true,
        },
        {
            name: "El Salvador Treasury",
            type: "Government",
            chain: "BTC",
            address: "1LQoWv",
            notes: "Trésorerie El Salvador",
            incomplete: true,
        },
    ],
};

/**
 * Obtenir les baleines par type
 */
export const getWhalesByType = (type) => {
    return CRYPTO_WHALES.whales.filter((whale) => whale.type === type);
};

/**
 * Obtenir les baleines par chaîne
 */
export const getWhalesByChain = (chain) => {
    return CRYPTO_WHALES.whales.filter((whale) => whale.chain === chain);
};

/**
 * Obtenir les baleines avec adresses complètes (non tronquées)
 */
export const getCompleteWhales = () => {
    return CRYPTO_WHALES.whales.filter((whale) => !whale.incomplete);
};

/**
 * Obtenir les baleines ETH uniquement (pour Moralis)
 */
export const getETHWhales = () => {
    return CRYPTO_WHALES.whales.filter(
        (whale) => whale.chain === "ETH" && !whale.incomplete
    );
};

/**
 * Rechercher une baleine par nom ou adresse
 */
export const searchWhale = (query) => {
    const lowerQuery = query.toLowerCase();
    return CRYPTO_WHALES.whales.filter(
        (whale) =>
            whale.name.toLowerCase().includes(lowerQuery) ||
            whale.address.toLowerCase().includes(lowerQuery) ||
            whale.type.toLowerCase().includes(lowerQuery)
    );
};

