/**
 * Liste des Hedge Funds majeurs à suivre
 * Source: Wikipedia - List of hedge funds (2024)
 */

export const HEDGE_FUNDS = {
  // Top 20 plus grands hedge funds (par AUM)
  top20: [
    { name: "Bridgewater Associates", cik: null, location: "Westport, CT, USA", aum: 89600 },
    { name: "Man Group", cik: null, location: "London, UK", aum: 77500 },
    { name: "Elliott Investment Management", cik: null, location: "West Palm Beach, FL, USA", aum: 69700 },
    { name: "Millennium Management, LLC", cik: null, location: "New York, NY, USA", aum: 67895 },
    { name: "Citadel LLC", cik: null, location: "Miami, FL, USA", aum: 63430 },
    { name: "The Children's Investment Fund Management", cik: null, location: "London, UK", aum: 63000 },
    { name: "D. E. Shaw & Co.", cik: null, location: "New York, NY, USA", aum: 53715 },
    { name: "Two Sigma", cik: null, location: "New York, NY, USA", aum: 44271 },
    { name: "Goldman Sachs Asset Management", cik: null, location: "New York, NY, USA", aum: 42000 },
    { name: "Farallon Capital", cik: null, location: "San Francisco, CA, USA", aum: 40300 },
    { name: "Renaissance Technologies", cik: null, location: "East Setauket, NY, USA", aum: 39200 },
    { name: "AQR Capital", cik: null, location: "Greenwich, CT, USA", aum: 38800 },
    { name: "Davidson Kempner Capital Management", cik: null, location: "New York, NY, USA", aum: 37000 },
    { name: "Point72 Asset Management", cik: null, location: "Stamford, CT, USA", aum: 35200 },
    { name: "Marshall Wace", cik: null, location: "London, UK", aum: 35171 },
    { name: "Brevan Howard", cik: null, location: "London, UK", aum: 31000 },
    { name: "Wellington Management Company", cik: null, location: "Boston, MA, USA", aum: 27800 },
    { name: "PIMCO", cik: null, location: "Newport Beach, CA, USA", aum: 27043 },
    { name: "Ruffer", cik: null, location: "London, UK", aum: 26857 },
    { name: "Anchorage Capital Group", cik: null, location: "New York, NY, USA", aum: 26800 },
  ],

  // Autres hedge funds notables (Amériques)
  notableAmericas: [
    "Acadian Asset Management",
    "Adage Capital Management",
    "Alphadyne Asset Management",
    "AlphaSimplex Group",
    "Altimeter Capital",
    "Angelo Gordon",
    "Appaloosa Management",
    "AQR Capital Management",
    "Archegos Capital Management",
    "Assured Investment Management",
    "Atlantic Investment Management",
    "Aurelius Capital Management",
    "Avenue Capital Group",
    "Baker Brothers Advisors",
    "Balyasny Asset Management",
    "Beach Point Capital Management",
    "Bracebridge Capital",
    "Canyon Capital Advisors",
    "Capstone Investment Advisors",
    "Coatue Management",
    "D1 Capital Partners",
    "Deerfield Management",
    "Discovery Capital Management",
    "Dragoneer Investment Group",
    "Ellington Management Group",
    "Engineers Gate",
    "ESL Investments",
    "ExodusPoint Capital Management",
    "Fortress Investment Group",
    "Garda Capital Partners",
    "GCM Grosvenor",
    "Glenview Capital Management",
    "GoldenTree Asset Management",
    "Graham Capital Management",
    "Gramercy Funds Management",
    "Greenlight Capital",
    "Harbinger Capital",
    "HBK Investments",
    "Highbridge Capital Management",
    "Highfields Capital Management",
    "Himalaya Capital",
    "Hudson Bay Capital Management",
    "Jain Global",
    "JANA Partners LLC",
    "K2 Advisors",
    "King Street Capital Management",
    "Lighthouse Investment Partners",
    "Lone Pine Capital",
    "Magnetar Capital",
    "Marathon Asset Management",
    "Maverick Capital",
    "Moore Capital Management",
    "OrbiMed",
    "Ospraie Management, LLC",
    "PanAgora Asset Management",
    "Pantera Capital",
    "Paulson & Co.",
    "PDT Partners",
    "Perceptive Advisors",
    "Pershing Square Capital Management",
    "RA Capital Management",
    "Revere Capital Advisors",
    "Saba Capital Management",
    "Schonfeld Strategic Advisors",
    "Scion Asset Management",
    "Sculptor Capital Management",
    "Silver Point Capital",
    "SkyBridge Capital",
    "SPX Capital",
    "Squarepoint Capital",
    "Statar Capital",
    "Sylebra Capital",
    "TGS Management",
    "Third Point Management",
    "Tiger Global Management",
    "Touradji Capital Management",
    "Trian Partners",
    "Tudor Investment Corporation",
    "Tsai Capital",
    "Universa Investments",
    "ValueAct Capital",
    "Verition Fund Management",
    "Viking Global Investors",
    "Voloridge Investment Management",
    "Walleye Capital",
    "Waterfall Asset Management",
    "WorldQuant",
    "Wynnefield Capital",
    "Voleon Group",
    "York Capital Management",
  ],

  // Hedge funds Asia-Pacific
  notableAsiaPacific: [
    "BFAM Partners",
    "Dymon Asia",
    "Greenwoods Asset Management",
    "High-Flyer",
    "Hillhouse Capital Group",
    "Lingjun Investment",
    "Maso Capital",
    "Minghong Investment",
    "Navigator Global Investments",
    "Oasis Management",
    "Perseverance Asset Management",
    "Pinpoint Asset Management",
    "Platinum Asset Management",
    "Quantedge",
    "Segantii Capital Management",
    "SPARX Group",
    "Tybourne Capital Management",
    "Ubiquant",
    "Value Partners",
    "Yanfu Investments",
  ],

  // Hedge funds EMEA
  notableEMEA: [
    "AKO Capital",
    "Aspect Capital",
    "BlueCrest Capital Management",
    "Capital Fund Management",
    "Capula Investment Management",
    "Caxton Associates",
    "Cheyne Capital",
    "CQS",
    "Egerton Capital",
    "Eisler Capital",
    "G-Research",
    "GLG Partners",
    "GSA Capital",
    "Lansdowne Partners",
    "LMR Partners",
    "Pharo Management",
    "Quality Capital Management",
    "Qube Research & Technologies",
    "Rokos Capital Management",
    "Scipion Capital",
    "Systematica Investments",
    "Toscafund Asset Management",
    "Winton Group",
  ],

  // Liste complète pour recherche
  getAll: function() {
    return [
      ...this.top20.map(f => f.name),
      ...this.notableAmericas,
      ...this.notableAsiaPacific,
      ...this.notableEMEA,
    ];
  },

  // Liste avec catégories
  getByCategory: function() {
    return {
      top20: this.top20,
      americas: this.notableAmericas.map(name => ({ name, category: "Americas" })),
      asiaPacific: this.notableAsiaPacific.map(name => ({ name, category: "Asia-Pacific" })),
      emea: this.notableEMEA.map(name => ({ name, category: "EMEA" })),
    };
  },
};

export default HEDGE_FUNDS;

